services:
  postgres:
    image: 'postgres:latest'
    container_name: ${DOCKER_CONTAINER_NAME}
    environment: # hibernate is going to handle the db creation for us.
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - "5432:5432"